version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.4

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - tox-{{ checksum "Pipfile.lock" }}

      - run:
          name: Set permissions
          command: |
            sudo chown -R circleci:circleci /usr/local/bin
            sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages

      - run:
          name: Install tox
          command: |
            pip install tox

      - run:
          name: Run tests
          command: |
            tox

      - save_cache:
          key: tox-{{ checksum "Pipfile.lock" }}
          paths:
            - ".tox"
